### ISSUE TITLE
Enhance sly tag creation

### ISSUE THREAD

**Issue by olmanslm** [parkerpierpont/HTL-Language-Support#1]
Hello, 

In order to follow the https://github.com/adobe/aem-core-wcm-components/wiki/htl-style-guide, I have a minor recommendation when we are adding <sly> elements. 

![image](https://user-images.githubusercontent.com/11982674/82254591-556db100-9910-11ea-820e-abc1a58725ca.png)

Please check the image above with the possible fix in order to use always <sly></sly>

**Comment by olmanslm** [comment]
`{
	"sly element with attribute": {
		"prefix": "sly",
		"body": "<sly data-sly-${1:0}></sly>"
	},
	"New Component with call to template file": {
		"prefix": "component",
		"body": "<sly data-sly-use.${1:data}=\"${2:template}.html\"\n\t\tdata-sly-call=\"${component.${2:template} @ properties=${3:properties}}\">$0</sly>"
	},
	"New template": {
		"prefix": "template",
		"body": "<template data-sly-template.${1:template}=\"${@ ${2:data}}\">$2</template>$0"
	}
}`
[enhance-sly-tag.txt](https://github.com/parkerpierpont/HTL-Language-Support/files/4646495/enhance-sly-tag.txt)

**Comment by parkerpierpont** [comment]
Merged pull request from @olmanslm that should resolve this issue. Thank you for your contribution!
